Authentication
DoubleAut/wished pull request #1
Opened 2023-11-11 18:35 UTC by RichardPickman

2023-11-16 14:21 UTC, zha13a commented
Уточняю...

- Не могу по нажатию enter войти, после ввода пароля, разве не должно быть так?
- letter-spacing у пароля (точки слипаются, нужен хотя бы 1px)
- Не следует ли вынести все текста в отдельный файл? Потом было бы проще делать перевод и пр. (widgets/auth/login/ui) (app/auth/page)
- В prettier стоит добавить максимальную длину строки... И наверное настройки prettier основать на каком-нибудь готов пакете, вроде air-bnb (shared/ui/input checkbox и пр.)
- Используемые цвета следует вынести в отдельные tailwind'овые константы (цвета ошибок, обычного текста, muted текста, я вижу, что они инкапсулированы в компоненте, но не везде и изменять их неудобно) (feature/auth/login/ui/Form)
- Маршруты к api не нужно вынести в отдельную константу? (api/auth/register/route)

2023-11-16 16:08 UTC, RichardPickman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add i18n mapper for localization and utilize them](https://trello.com/c/WEIC5hE4/1-add-i18n-mapper-for-localization-and-utilize-them)

2023-11-16 16:12 UTC, RichardPickman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix forms logic to utilize keydown events](https://trello.com/c/WenDkLzI/4-fix-forms-logic-to-utilize-keydown-events)

2023-11-16 16:12 UTC, RichardPickman commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add constants for Auth pull request](https://trello.com/c/yJo9JHnP/5-add-constants-for-auth-pull-request)

2023-11-17 18:18 UTC, RichardPickman commented
> ![](https://camo.githubusercontent.com/208d50cabd9d101500fe5dd548265dcfa00e017e397395692a173e7116c1094a/68747470733a2f2f6769746875622e7472656c6c6f2e73657276696365732f696d616765732f6d696e692d7472656c6c6f2d69636f6e2e706e67) [Fix forms logic to utilize keydown events](https://trello.com/c/WenDkLzI/4-fix-forms-logic-to-utilize-keydown-events)

Made a submit event listener hook for that purposes.


CHECK PR 👉🏻👈🏻

2023-11-20 13:36 UTC, zha13a commented on pnpm-lock.yaml
>    '@radix-ui/react-slot':
Нам точно нужен pnpm-lock в репе?

2023-11-20 13:36 UTC, zha13a commented on src/app/api/auth/[...nextauth]/services/user.ts
> +export const isPasswordsEqual = async (password: string, hash: string) =>
Валидация пароля должна быть в сервисах пользователя? :nerd_face:

2023-11-20 13:36 UTC, zha13a commented on src/app/api/auth/[...nextauth]/services/tokens.ts
> +interface Tokens {
Наверное правильней будет interface Token :nerd_face:
Дальше по коду будет "type UserTokensResponse = Tokens | null;", кажется, что тут должен быть массив токенов

2023-11-20 13:36 UTC, zha13a commented on src/app/api/auth/[...nextauth]/services/tokens.ts
> +export const saveTokens = async (user: StrippedUser, tokens: any) => {
Хмм, есть же тип Token? Почему тут any? Если я правильно понимаю, так как раз важно, чтобы в эту функцию прилетал токен

2023-11-20 13:36 UTC, zha13a commented on src/app/api/auth/[...nextauth]/route.ts
>                      throw new Error('Credentials are wrong!');
Я чот не помню, говорили ли мы о том, чтобы вынести все сообщения об ошибках в отдельный файл... Либо это будет вместе с i18n? 
https://media.tenor.com/xVckG2XLl1oAAAAC/gavin-im-confused.gif

2023-11-20 13:36 UTC, zha13a commented on src/app/api/auth/[...nextauth]/route.ts
> +            if (Date.now() < token.accessTokenExpiresIn) {
Сравнение настоящего времени с длительностью хранения токена? 👎🏻
(Чекни плиз, я не выкупаю чот, что там хранится)

2023-11-20 13:36 UTC, zha13a commented on src/shared/lib/hooks/useSubmitListener/index.tsx
> +            if (isEnter || isNumpadEnter) {
Тут не нужна вторая проверка, если ты выше проверил, что это именно или Enter, или NumpadEnter

2023-11-21 12:47 UTC, RichardPickman commented on src/app/api/auth/[...nextauth]/services/user.ts
> +export const isPasswordsEqual = async (password: string, hash: string) =>
It's server-side part of application, so I cannot merge them with frontend part

2023-11-21 14:20 UTC, RichardPickman commented on pnpm-lock.yaml
>    '@radix-ui/react-slot':
![image](https://github.com/DoubleAut/wished/assets/65208028/77067fce-a558-4010-8c3a-3a57672911d6)
Unfortunately, YES. Shadcn button component utilizes that package....

2023-11-21 14:21 UTC, RichardPickman commented on src/app/api/auth/[...nextauth]/services/tokens.ts
> +interface Tokens {
right

2023-11-21 14:26 UTC, RichardPickman commented on src/shared/lib/hooks/useSubmitListener/index.tsx
> +            if (isEnter || isNumpadEnter) {
did a small refactor

2023-11-22 09:42 UTC, RichardPickman commented on src/app/api/auth/[...nextauth]/services/tokens.ts
> +export const saveTokens = async (user: StrippedUser, tokens: any) => {
fixed, my man

2023-11-22 09:43 UTC, RichardPickman commented on src/app/api/auth/[...nextauth]/route.ts
>                      throw new Error('Credentials are wrong!');
Ummm... Sounds unpromising, should speak up about it 😎

2023-11-24 15:50 UTC, RichardPickman commented on src/app/api/auth/[...nextauth]/route.ts
>                      throw new Error('Credentials are wrong!');
Yeah, will bound that errors with i18n!
// TODO: Create a card on trello!

2023-11-24 16:41 UTC, zha13a requested changes

2023-11-24 16:41 UTC, zha13a commented on src/shared/lib/hooks/useSubmitListener/index.tsx
> -            if (!isEnter && !isNumpadEnter) {
I guess you should early return instead...

2023-11-24 16:41 UTC, zha13a commented on src/app/api/auth/[...nextauth]/route.ts
> +    providers: providers,
Зачеммммм........

2023-12-06 19:47 UTC, zha13a approved these changes
All good and dandy, i guess

2023-12-07 16:19 UTC, merged